<Project Sdk="Microsoft.NET.Sdk">

  <!-- 共享编译设定见 Directory.Build.props；包版本见 Directory.Packages.props -->
  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenClockTower.Rules\OpenClockTower.Rules.csproj" />
  </ItemGroup>

</Project>
